## YAML Template.
name: PlayerManagement
main: com.mahn42.bart4223.PlayerManagement.PlayerManagement
version: 0.9
depend: [MAHN42-Framework]
commands:
   pm_pslist:
      description: list player statistic
      usage: /pm_pslist [<Playername>]
      aliases: pmpsl
   pm_pstop:
      description: top player statistic
      usage: /pm_pstop
      aliases: pmpst
   pm_pnadd:
      description: add a player news
      usage: /pm_pnadd
      aliases: pmpna
   pm_pnlist:
      description: list the player news
      usage: /pm_pnlist
      aliases: pmpnl
   pm_splist:
      description: list player social points
      usage: /pm_splist [<Playername>|all]
      aliases: pmspl
   pm_warning:
      description: utters a player warning
      usage: /pm_warning <Playername> <Points> <Reason>
      aliases: pmw
   pm_warninglist:
      description: list all player warnings
      usage: /pm_warninglist [<Playername>]
      aliases: pmwl
   pm_warningpoints:
      description: list player warning points
      usage: /pm_warningpoints[<Playername>|all]
      aliases: pmwp
